; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32


[env:esp32]
; platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32.git#develop 
; board = esp32dev
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = ./board_partitions/default.csv
build_flags =
  -w
  -D CORE_DEBUG_LEVEL=5
  -D CONFIG_ARDUHAL_LOG_COLORS=1


; ESP-Insight Firmware data configurations for the scripts:
custom_prog_name = FirmwareNameTest
custom_prog_version = 1.2.3
custom_appinfos_patch_builder = false

extra_scripts =
    ./scripts/custom_pio_tasks.py

    ;; Modify the filename of output elf/bin program binaries,
    ;; from `firmare.elf/bin` --> `<project-name>-<project-version>.elf/bin`
    pre:./scripts/progname.py

    ; Write project name/version & build-date
    ;; at the beggining of the firmware-image
    ;; for OTA code to know what is loaded in each partition.
    ;; NOTE: doing this otherwise would require recompiling esp_idf booloader.
    post:./scripts/patchappinfos.py

    ; Create a zip file ready to upload to ESP-Insights platform
    post:./scripts/pack_firmware.py